x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://10.129.0.5:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 3
      loki-max-backoff: 1000ms
      loki-timeout: 1s
services:
  api:
    <<: *default-logging
    image: ${TAG}
    container_name: "${PROJECT_NAME}-backend"
    ports:
      - 8080:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: "${DB_URL}"

  postgres:
    <<: *default-logging
    image: postgres:13
    container_name: "${PROJECT_NAME}-db"
    volumes:
      - pg_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "api"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 90s
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${DB}"
    ports:
      - 5432:5432

volumes:
  pg_data: 
